### PR TITLE
Rename Product Family to Classification. Added ability to link few Classifications with Product

### PR DESCRIPTION
**Pull request by rratsun**

### CODE REVIEW

**Comment by marcus-at-localhost** [comment]
This seems like a bigger change any chance to get a more extensive description when finally released? Do we have to expect any API changes? Thanks!

**Comment by rratsun** [comment]
ProductFamily renamed to Classification. ProductFamilyAttribute renamed to ClassificationAttribute. So yeah, API changed because ProductFamily and ProductFamilyAttribute Controllers disappeared. More over, with the next minor version we added the ability to choose a few classifications(productFamilies) in the product. It's mean that field productFamily in Product entity disappeared, but classifications created instead of old field.

**Comment by rratsun** [comment]
It will be available with version PIM 1.8.0

**Comment by marcus-at-localhost** [comment]
@rratsun thanks for the info.
Would you update the docs in time and/or be able to write a detailed changelog, with endpoint changes?
That sounds like big changes to clients that consume the API. I'm going to be anxious to press that Update button. :)

**Pull request merged**
